/*
 Highcharts JS v8.0.0 (2020-02-26)

 Sonification module

 (c) 2012-2019 ystein Moseng

 License: www.highcharts.com/license
*/
(function(b){"object"===typeof module&&module.exports?(b["default"]=b,module.exports=b):"function"===typeof define&&define.amd?define("highcharts/modules/sonification",["highcharts"],function(n){b(n);b.Highcharts=n;return b}):b("undefined"!==typeof Highcharts?Highcharts:void 0)})(function(b){function n(d,b,e,p){d.hasOwnProperty(b)||(d[b]=p.apply(null,e))}b=b?b._modules:{};n(b,"modules/sonification/Instrument.js",[b["parts/Globals.js"],b["parts/Utilities.js"]],function(d,b){function e(c){this.init(c)}
var p=b.error,m=b.merge,g=b.pick,q=b.uniqueKey,k={type:"oscillator",playCallbackInterval:20,oscillator:{waveformShape:"sine"}};e.prototype.init=function(c){this.initAudioContext()?(this.options=m(k,c),this.id=this.options.id=c&&c.id||q(),c=d.audioContext,this.gainNode=c.createGain(),this.setGain(0),(this.panNode=c.createStereoPanner&&c.createStereoPanner())?(this.setPan(0),this.gainNode.connect(this.panNode),this.panNode.connect(c.destination)):this.gainNode.connect(c.destination),"oscillator"===
this.options.type&&this.initOscillator(this.options.oscillator),this.playCallbackTimers=[]):p(29)};e.prototype.copy=function(c){return new e(m(this.options,{id:null},c))};e.prototype.initAudioContext=function(){var c=d.win.AudioContext||d.win.webkitAudioContext,a=!!d.audioContext;return c?(d.audioContext=d.audioContext||new c,!a&&d.audioContext&&"running"===d.audioContext.state&&d.audioContext.suspend(),!!(d.audioContext&&d.audioContext.createOscillator&&d.audioContext.createGain)):!1};e.prototype.initOscillator=
function(c){this.oscillator=d.audioContext.createOscillator();this.oscillator.type=c.waveformShape;this.oscillator.connect(this.gainNode);this.oscillatorStarted=!1};e.prototype.setPan=function(c){this.panNode&&this.panNode.pan.setValueAtTime(c,d.audioContext.currentTime)};e.prototype.setGain=function(c,a){this.gainNode&&(1.2<c&&(console.warn("Highcharts sonification warning: Volume of instrument set too high."),c=1.2),a?(this.gainNode.gain.setValueAtTime(this.gainNode.gain.value,d.audioContext.currentTime),
this.gainNode.gain.linearRampToValueAtTime(c,d.audioContext.currentTime+a/1E3)):this.gainNode.gain.setValueAtTime(c,d.audioContext.currentTime))};e.prototype.cancelGainRamp=function(){this.gainNode&&this.gainNode.gain.cancelScheduledValues(0)};e.prototype.getValidFrequency=function(c,a,f){var h=this.options.allowedFrequencies,d=g(f,Infinity),b=g(a,-Infinity);return h&&h.length?h.reduce(function(a,f){return Math.abs(f-c)<Math.abs(a-c)&&f<d&&f>b?f:a},Infinity):c};e.prototype.clearPlayCallbackTimers=
function(){this.playCallbackTimers.forEach(function(c){clearInterval(c)});this.playCallbackTimers=[]};e.prototype.setFrequency=function(c,a){a=a||{};c=this.getValidFrequency(c,a.min,a.max);"oscillator"===this.options.type&&this.oscillatorPlay(c)};e.prototype.oscillatorPlay=function(c){this.oscillatorStarted||(this.oscillator.start(),this.oscillatorStarted=!0);this.oscillator.frequency.setValueAtTime(c,d.audioContext.currentTime)};e.prototype.preparePlay=function(){this.setGain(.001);"suspended"===
d.audioContext.state&&d.audioContext.resume();this.oscillator&&!this.oscillatorStarted&&(this.oscillator.start(),this.oscillatorStarted=!0)};e.prototype.play=function(c){var a=this,f=c.duration||0,h=function(f,d,h){var b=c.duration,e=0,k=a.options.playCallbackInterval;if("function"===typeof f){var g=setInterval(function(){e++;var c=e*k/b;if(1<=c)a[d](f(1),h),clearInterval(g);else a[d](f(c),h)},k);a.playCallbackTimers.push(g)}else a[d](f,h)};if(a.id)if("suspended"===d.audioContext.state||this.oscillator&&
!this.oscillatorStarted)a.preparePlay(),setTimeout(function(){a.play(c)},10);else{a.playCallbackTimers.length&&a.clearPlayCallbackTimers();a.cancelGainRamp();a.stopOscillatorTimeout&&(clearTimeout(a.stopOscillatorTimeout),delete a.stopOscillatorTimeout);a.stopTimeout&&(clearTimeout(a.stopTimeout),delete a.stopTimeout,a.stopCallback&&(a._play=a.play,a.play=function(){},a.stopCallback("cancelled"),a.play=a._play));var b=f<d.sonification.fadeOutDuration+20;a.stopCallback=c.onEnd;var e=function(){delete a.stopTimeout;
a.stop(b)};f?(a.stopTimeout=setTimeout(e,b?f:f-d.sonification.fadeOutDuration),h(c.frequency,"setFrequency",{minFrequency:c.minFrequency,maxFrequency:c.maxFrequency}),h(g(c.volume,1),"setGain",4),h(g(c.pan,0),"setPan")):e()}};e.prototype.mute=function(){this.setGain(.0001,.8*d.sonification.fadeOutDuration)};e.prototype.stop=function(c,a,f){var h=this,b=function(){h.stopOscillatorTimeout&&delete h.stopOscillatorTimeout;try{h.oscillator.stop()}catch(u){}h.oscillator.disconnect(h.gainNode);h.initOscillator(h.options.oscillator);
a&&a(f);h.stopCallback&&h.stopCallback(f)};h.playCallbackTimers.length&&h.clearPlayCallbackTimers();h.stopTimeout&&clearTimeout(h.stopTimeout);c?(h.setGain(0),b()):(h.mute(),h.stopOscillatorTimeout=setTimeout(b,d.sonification.fadeOutDuration+100))};return e});n(b,"modules/sonification/musicalFrequencies.js",[],function(){return[16.351597831287414,17.323914436054505,18.354047994837977,19.445436482630058,20.601722307054366,21.826764464562746,23.12465141947715,24.499714748859326,25.956543598746574,27.5,
29.13523509488062,30.86770632850775,32.70319566257483,34.64782887210901,36.70809598967594,38.890872965260115,41.20344461410875,43.653528929125486,46.2493028389543,48.999429497718666,51.91308719749314,55,58.27047018976124,61.7354126570155,65.40639132514966,69.29565774421802,73.41619197935188,77.78174593052023,82.4068892282175,87.30705785825097,92.4986056779086,97.99885899543733,103.82617439498628,110,116.54094037952248,123.47082531403103,130.8127826502993,138.59131548843604,146.8323839587038,155.56349186104046,
164.81377845643496,174.61411571650194,184.9972113558172,195.99771799087463,207.65234878997256,220,233.08188075904496,246.94165062806206,261.6255653005986,277.1826309768721,293.6647679174076,311.1269837220809,329.6275569128699,349.2282314330039,369.9944227116344,391.99543598174927,415.3046975799451,440,466.1637615180899,493.8833012561241,523.2511306011972,554.3652619537442,587.3295358348151,622.2539674441618,659.2551138257398,698.4564628660078,739.9888454232688,783.9908719634985,830.6093951598903,
880,932.3275230361799,987.7666025122483,1046.5022612023945,1108.7305239074883,1174.6590716696303,1244.5079348883237,1318.5102276514797,1396.9129257320155,1479.9776908465376,1567.981743926997,1661.2187903197805,1760,1864.6550460723597,1975.533205024496,2093.004522404789,2217.4610478149766,2349.31814333926,2489.0158697766474,2637.02045530296,2793.825851464031,2959.955381693075,3135.9634878539946,3322.437580639561,3520,3729.3100921447194,3951.066410048992,4186.009044809578]});n(b,"modules/sonification/utilities.js",
[b["modules/sonification/musicalFrequencies.js"],b["parts/Utilities.js"]],function(d,b){function e(b){this.init(b||[])}var p=b.clamp;e.prototype.init=function(b){this.supportedSignals=b;this.signals={}};e.prototype.registerSignalCallbacks=function(b){var d=this;d.supportedSignals.forEach(function(e){var k=b[e];k&&(d.signals[e]=d.signals[e]||[]).push(k)})};e.prototype.clearSignalCallbacks=function(b){var d=this;b?b.forEach(function(b){d.signals[b]&&delete d.signals[b]}):d.signals={}};e.prototype.emitSignal=
function(b,d){var e;this.signals[b]&&this.signals[b].forEach(function(b){b=b(d);e="undefined"!==typeof b?b:e});return e};return{musicalFrequencies:d,SignalHandler:e,getMusicalScale:function(b){return d.filter(function(d,e){var k=e%12+1;return b.some(function(c){return c===k})})},calculateDataExtremes:function(b,d){return b.series.reduce(function(b,e){e.points.forEach(function(c){c="undefined"!==typeof c[d]?c[d]:c.options[d];b.min=Math.min(b.min,c);b.max=Math.max(b.max,c)});return b},{min:Infinity,
max:-Infinity})},virtualAxisTranslate:function(b,d,e){var k=d.max-d.min;b=e.min+(e.max-e.min)*(b-d.min)/k;return 0<k?p(b,e.min,e.max):e.min}}});n(b,"modules/sonification/instrumentDefinitions.js",[b["modules/sonification/Instrument.js"],b["modules/sonification/utilities.js"]],function(b,l){var d={};["sine","square","triangle","sawtooth"].forEach(function(e){d[e]=new b({oscillator:{waveformShape:e}});d[e+"Musical"]=new b({allowedFrequencies:l.musicalFrequencies,oscillator:{waveformShape:e}});d[e+"Major"]=
new b({allowedFrequencies:l.getMusicalScale([1,3,5,6,8,10,12]),oscillator:{waveformShape:e}})});return d});n(b,"modules/sonification/Earcon.js",[b["parts/Globals.js"],b["parts/Utilities.js"]],function(b,l){function d(b){this.init(b||{})}var p=l.error,m=l.merge,g=l.pick,q=l.uniqueKey;d.prototype.init=function(b){this.options=b;this.options.id||(this.options.id=this.id=q());this.instrumentsPlaying={}};d.prototype.sonify=function(d){var c=m(this.options,d),a=g(c.volume,1),f=c.pan,e=this,k=d&&d.onEnd,
u=e.options.onEnd;c.instruments.forEach(function(c){var d="string"===typeof c.instrument?b.sonification.instruments[c.instrument]:c.instrument,h=m(c.playOptions),l="";if(d&&d.play){if(c.playOptions){"function"!==typeof c.playOptions.volume&&(h.volume=g(a,1)*g(c.playOptions.volume,1));h.pan=g(f,h.pan);var r=h.onEnd;h.onEnd=function(){delete e.instrumentsPlaying[l];r&&r.apply(this,arguments);Object.keys(e.instrumentsPlaying).length||(k&&k.apply(this,arguments),u&&u.apply(this,arguments))};c=d.copy();
l=c.id;e.instrumentsPlaying[l]=c;c.play(h)}}else p(30)})};d.prototype.cancelSonify=function(b){var c=this.instrumentsPlaying,a=c&&Object.keys(c);a&&a.length&&(a.forEach(function(a){c[a].stop(!b,null,"cancelled")}),this.instrumentsPlaying={})};return d});n(b,"modules/sonification/pointSonify.js",[b["parts/Globals.js"],b["parts/Utilities.js"],b["modules/sonification/utilities.js"]],function(b,l,e){var d=l.error,m=l.merge,g=l.pick,q={minDuration:20,maxDuration:2E3,minVolume:.1,maxVolume:1,minPan:-1,
maxPan:1,minFrequency:220,maxFrequency:2200};return{pointSonify:function(k){var c=this,a=c.series.chart,f=k.dataExtremes||{},h=function(a,b,d){return"function"===typeof a?b?function(b){return a(c,f,b)}:a(c,f):"string"===typeof a?(f[a]=f[a]||e.calculateDataExtremes(c.series.chart,a),e.virtualAxisTranslate(g(c[a],c.options[a]),f[a],d)):a};a.sonification.currentlyPlayingPoint=c;c.sonification=c.sonification||{};c.sonification.instrumentsPlaying=c.sonification.instrumentsPlaying||{};var l=c.sonification.signalHandler=
c.sonification.signalHandler||new e.SignalHandler(["onEnd"]);l.clearSignalCallbacks();l.registerSignalCallbacks({onEnd:k.onEnd});!c.isNull&&c.visible&&c.series.visible?k.instruments.forEach(function(e){var f="string"===typeof e.instrument?b.sonification.instruments[e.instrument]:e.instrument,k=e.instrumentMapping||{},g=m(q,e.instrumentOptions),p=f.id,r=function(b){e.onEnd&&e.onEnd.apply(this,arguments);a.sonification&&a.sonification.currentlyPlayingPoint&&delete a.sonification.currentlyPlayingPoint;
c.sonification&&c.sonification.instrumentsPlaying&&(delete c.sonification.instrumentsPlaying[p],Object.keys(c.sonification.instrumentsPlaying).length||l.emitSignal("onEnd",b))};f&&f.play?(c.sonification.instrumentsPlaying[f.id]=f,f.play({frequency:h(k.frequency,!0,{min:g.minFrequency,max:g.maxFrequency}),duration:h(k.duration,!1,{min:g.minDuration,max:g.maxDuration}),pan:h(k.pan,!0,{min:g.minPan,max:g.maxPan}),volume:h(k.volume,!0,{min:g.minVolume,max:g.maxVolume}),onEnd:r,minFrequency:g.minFrequency,
maxFrequency:g.maxFrequency})):d(30)}):l.emitSignal("onEnd")},pointCancelSonify:function(b){var c=this.sonification&&this.sonification.instrumentsPlaying,a=c&&Object.keys(c);a&&a.length&&(a.forEach(function(a){c[a].stop(!b,null,"cancelled")}),this.sonification.instrumentsPlaying={},this.sonification.signalHandler.emitSignal("onEnd","cancelled"))}}});n(b,"modules/sonification/chartSonify.js",[b["parts/Globals.js"],b["parts/Point.js"],b["parts/Utilities.js"],b["modules/sonification/utilities.js"]],
function(b,l,e,p){function d(a,b){return"function"===typeof b?b(a):w(a[b],a.options[b])}function g(a,b){return a.points.reduce(function(a,c){c=d(c,b);a.min=Math.min(a.min,c);a.max=Math.max(a.max,c);return a},{min:Infinity,max:-Infinity})}function q(a,b,c){return(b||[]).reduce(function(b,c){Object.keys(c.instrumentMapping||{}).forEach(function(d){d=c.instrumentMapping[d];"string"!==typeof d||b[d]||(b[d]=p.calculateDataExtremes(a,d))});return b},v(c))}function k(a,c){return c.reduce(function(c,d){var e=
d.earcon;d.condition?(d=d.condition(a),d instanceof b.sonification.Earcon?c.push(d):d&&c.push(e)):d.onPoint&&a.id===d.onPoint&&c.push(e);return c},[])}function c(a){return a.map(function(a){var c=a.instrument;c=("string"===typeof c?b.sonification.instruments[c]:c).copy();return v(a,{instrument:c})})}function a(a,e){var f=e.timeExtremes||g(a,e.pointPlayTime,e.dataExtremes),h=q(a.chart,e.instruments,e.dataExtremes),C=c(e.instruments),D=a.points.reduce(function(a,c){var g=k(c,e.earcons||[]),x=p.virtualAxisTranslate(d(c,
e.pointPlayTime),f,{min:0,max:e.duration});return a.concat(new b.sonification.TimelineEvent({eventObject:c,time:x,id:c.id,playOptions:{instruments:C,dataExtremes:h}}),g.map(function(a){return new b.sonification.TimelineEvent({eventObject:a,time:x})}))},[]);return new b.sonification.TimelinePath({events:D,onStart:function(){if(e.onStart)e.onStart(a)},onEventStart:function(a){var b=a.options&&a.options.eventObject;if(b instanceof l){if(!b.series.visible&&!b.series.chart.series.some(function(a){return a.visible}))return a.timelinePath.timeline.pause(),
a.timelinePath.timeline.resetCursor(),!1;if(e.onPointStart)e.onPointStart(a,b)}},onEventEnd:function(a){var b=a.event&&a.event.options&&a.event.options.eventObject;if(b instanceof l&&e.onPointEnd)e.onPointEnd(a.event,b)},onEnd:function(){if(e.onEnd)e.onEnd(a)}})}function f(a,b,c){var e=c.seriesOptions||{};return v({dataExtremes:b,timeExtremes:g(a,c.pointPlayTime),instruments:c.instruments,onStart:c.onSeriesStart,onEnd:c.onSeriesEnd,earcons:c.earcons},B(e)?A(e,function(b){return b.id===w(a.id,a.options.id)})||
{}:e,{pointPlayTime:c.pointPlayTime})}function h(a,c,e){if("sequential"===a||"simultaneous"===a){var d=c.series.reduce(function(a,b){b.visible&&a.push({series:b,seriesOptions:e(b)});return a},[]);"simultaneous"===a&&(d=[d])}else d=a.reduce(function(a,d){d=t(d).reduce(function(a,d){var f;if("string"===typeof d){var h=c.get(d);h.visible&&(f={series:h,seriesOptions:e(h)})}else d instanceof b.sonification.Earcon&&(f=new b.sonification.TimelinePath({events:[new b.sonification.TimelineEvent({eventObject:d})]}));
d.silentWait&&(f=new b.sonification.TimelinePath({silentWait:d.silentWait}));f&&a.push(f);return a},[]);d.length&&a.push(d);return a},[]);return d}function r(a,c){return c?a.reduce(function(d,e,f){e=t(e);d.push(e);f<a.length-1&&e.some(function(a){return a.series})&&d.push(new b.sonification.TimelinePath({silentWait:c}));return d},[]):a}function u(a){return a.reduce(function(a,b){b=t(b);return a+(1===b.length&&b[0].options&&b[0].options.silentWait||0)},0)}function n(a){var c=a.reduce(function(a,b){(b=
b.events)&&b.length&&(a.min=Math.min(b[0].time,a.min),a.max=Math.max(b[b.length-1].time,a.max));return a},{min:Infinity,max:-Infinity});a.forEach(function(a){var d=a.events,e=d&&d.length,f=[];e&&d[0].time<=c.min||f.push(new b.sonification.TimelineEvent({time:c.min}));e&&d[d.length-1].time>=c.max||f.push(new b.sonification.TimelineEvent({time:c.max}));f.length&&a.addTimelineEvents(f)})}function y(a){return a.reduce(function(a,b){return a+t(b).reduce(function(a,b){return(b=b.series&&b.seriesOptions&&
b.seriesOptions.timeExtremes)?Math.max(a,b.max-b.min):a},0)},0)}function z(c,d){var e=Math.max(d-u(c),0),f=y(c);return c.reduce(function(c,d){d=t(d).reduce(function(c,d){d instanceof b.sonification.TimelinePath?c.push(d):d.series&&(d.seriesOptions.duration=d.seriesOptions.duration||p.virtualAxisTranslate(d.seriesOptions.timeExtremes.max-d.seriesOptions.timeExtremes.min,{min:0,max:f},{min:0,max:e}),c.push(a(d.series,d.seriesOptions)));return c},[]);c.push(d);return c},[])}"";var A=e.find,B=e.isArray,
v=e.merge,w=e.pick,t=e.splat;return{chartSonify:function(a){this.sonification.timeline&&this.sonification.timeline.pause();var c=q(this,a.instruments,a.dataExtremes),d=h(a.order,this,function(b){return f(b,c,a)});d=r(d,a.afterSeriesWait||0);d=z(d,a.duration);d.forEach(function(a){n(a)});this.sonification.timeline=new b.sonification.Timeline({paths:d,onEnd:a.onEnd});this.sonification.timeline.play()},seriesSonify:function(c){c=a(this,c);var d=this.chart.sonification;d.timeline&&d.timeline.pause();
d.timeline=new b.sonification.Timeline({paths:[c]});d.timeline.play()},pause:function(a){this.sonification.timeline?this.sonification.timeline.pause(w(a,!0)):this.sonification.currentlyPlayingPoint&&this.sonification.currentlyPlayingPoint.cancelSonify(a)},resume:function(a){this.sonification.timeline&&this.sonification.timeline.play(a)},rewind:function(a){this.sonification.timeline&&this.sonification.timeline.rewind(a)},cancel:function(a){this.pauseSonify(a);this.resetSonifyCursor()},getCurrentPoints:function(){if(this.sonification.timeline){var a=
this.sonification.timeline.getCursor();return Object.keys(a).map(function(b){return a[b].eventObject}).filter(function(a){return a instanceof l})}return[]},setCursor:function(a){var b=this.sonification.timeline;b&&t(a).forEach(function(a){b.setCursor(a.id)})},resetCursor:function(){this.sonification.timeline&&this.sonification.timeline.resetCursor()},resetCursorEnd:function(){this.sonification.timeline&&this.sonification.timeline.resetCursorEnd()}}});n(b,"modules/sonification/Timeline.js",[b["parts/Globals.js"],
b["parts/Utilities.js"],b["modules/sonification/utilities.js"]],function(b,l,e){function d(a){this.init(a||{})}function m(a){this.init(a)}function g(a){this.init(a||{})}var n=l.merge,k=l.splat,c=l.uniqueKey;d.prototype.init=function(a){this.options=a;this.time=a.time||0;this.id=this.options.id=a.id||c()};d.prototype.play=function(a){var b=this.options.eventObject,c=this.options.onEnd,d=a&&a.onEnd,e=this.options.playOptions&&this.options.playOptions.onEnd;a=n(this.options.playOptions,a);b&&b.sonify?
(a.onEnd=c||d||e?function(){var a=arguments;[c,d,e].forEach(function(b){b&&b.apply(this,a)})}:void 0,b.sonify(a)):(d&&d(),c&&c())};d.prototype.cancel=function(a){this.options.eventObject.cancelSonify(a)};m.prototype.init=function(a){this.options=a;this.id=this.options.id=a.id||c();this.cursor=0;this.eventsPlaying={};this.events=a.silentWait?[new d({time:0}),new d({time:a.silentWait})]:this.options.events;this.sortEvents();this.updateEventIdMap();this.signalHandler=new e.SignalHandler(["playOnEnd",
"masterOnEnd","onStart","onEventStart","onEventEnd"]);this.signalHandler.registerSignalCallbacks(n(a,{masterOnEnd:a.onEnd}))};m.prototype.sortEvents=function(){this.events=this.events.sort(function(a,b){return a.time-b.time})};m.prototype.updateEventIdMap=function(){this.eventIdMap=this.events.reduce(function(a,b,c){a[b.id]=c;return a},{})};m.prototype.addTimelineEvents=function(a){this.events=this.events.concat(a);this.sortEvents();this.updateEventIdMap()};m.prototype.getCursor=function(){return this.events[this.cursor]};
m.prototype.setCursor=function(a){a=this.eventIdMap[a];return"undefined"!==typeof a?(this.cursor=a,!0):!1};m.prototype.play=function(a){this.pause();this.signalHandler.emitSignal("onStart");this.signalHandler.clearSignalCallbacks(["playOnEnd"]);this.signalHandler.registerSignalCallbacks({playOnEnd:a});this.playEvents(1)};m.prototype.rewind=function(a){this.pause();this.signalHandler.emitSignal("onStart");this.signalHandler.clearSignalCallbacks(["playOnEnd"]);this.signalHandler.registerSignalCallbacks({playOnEnd:a});
this.playEvents(-1)};m.prototype.resetCursor=function(){this.cursor=0};m.prototype.resetCursorEnd=function(){this.cursor=this.events.length-1};m.prototype.pause=function(a){var b=this;clearTimeout(b.nextScheduledPlay);Object.keys(b.eventsPlaying).forEach(function(c){b.eventsPlaying[c]&&b.eventsPlaying[c].cancel(a)});b.eventsPlaying={}};m.prototype.playEvents=function(a){var b=this,c=b.events[this.cursor],d=b.events[this.cursor+a],e=function(a){b.signalHandler.emitSignal("masterOnEnd",a);b.signalHandler.emitSignal("playOnEnd",
a)};c.timelinePath=b;if(!1===b.signalHandler.emitSignal("onEventStart",c))e({event:c,cancelled:!0});else if(b.eventsPlaying[c.id]=c,c.play({onEnd:function(a){a={event:c,cancelled:!!a};delete b.eventsPlaying[c.id];b.signalHandler.emitSignal("onEventEnd",a);d||e(a)}}),d){var g=Math.abs(d.time-c.time);1>g?(b.cursor+=a,b.playEvents(a)):this.nextScheduledPlay=setTimeout(function(){b.cursor+=a;b.playEvents(a)},g)}};g.prototype.init=function(a){this.options=a;this.cursor=0;this.paths=a.paths;this.pathsPlaying=
{};this.signalHandler=new e.SignalHandler(["playOnEnd","masterOnEnd","onPathStart","onPathEnd"]);this.signalHandler.registerSignalCallbacks(n(a,{masterOnEnd:a.onEnd}))};g.prototype.play=function(a){this.pause();this.signalHandler.clearSignalCallbacks(["playOnEnd"]);this.signalHandler.registerSignalCallbacks({playOnEnd:a});this.playPaths(1)};g.prototype.rewind=function(a){this.pause();this.signalHandler.clearSignalCallbacks(["playOnEnd"]);this.signalHandler.registerSignalCallbacks({playOnEnd:a});this.playPaths(-1)};
g.prototype.playPaths=function(a){var c=k(this.paths[this.cursor]),d=this.paths[this.cursor+a],e=this,g=this.signalHandler,l=0,m=function(b){g.emitSignal("onPathStart",b);e.pathsPlaying[b.id]=b;b[0<a?"play":"rewind"](function(f){f=f&&f.cancelled;var h={path:b,cancelled:f};delete e.pathsPlaying[b.id];g.emitSignal("onPathEnd",h);l++;l>=c.length&&(d&&!f?(e.cursor+=a,k(d).forEach(function(b){b[0<a?"resetCursor":"resetCursorEnd"]()}),e.playPaths(a)):(g.emitSignal("playOnEnd",h),g.emitSignal("masterOnEnd",
h)))})};c.forEach(function(a){a&&(a.timeline=e,setTimeout(function(){m(a)},b.sonification.fadeOutDuration))})};g.prototype.pause=function(a){var b=this;Object.keys(b.pathsPlaying).forEach(function(c){b.pathsPlaying[c]&&b.pathsPlaying[c].pause(a)});b.pathsPlaying={}};g.prototype.resetCursor=function(){this.paths.forEach(function(a){k(a).forEach(function(a){a.resetCursor()})});this.cursor=0};g.prototype.resetCursorEnd=function(){this.paths.forEach(function(a){k(a).forEach(function(a){a.resetCursorEnd()})});
this.cursor=this.paths.length-1};g.prototype.setCursor=function(a){return this.paths.some(function(b){return k(b).some(function(b){return b.setCursor(a)})})};g.prototype.getCursor=function(){return this.getCurrentPlayingPaths().reduce(function(a,b){a[b.id]=b.getCursor();return a},{})};g.prototype.atStart=function(){return!this.getCurrentPlayingPaths().some(function(a){return a.cursor})};g.prototype.getCurrentPlayingPaths=function(){return k(this.paths[this.cursor])};return{TimelineEvent:d,TimelinePath:m,
Timeline:g}});n(b,"modules/sonification/sonification.js",[b["parts/Globals.js"],b["parts/Point.js"],b["parts/Utilities.js"],b["modules/sonification/Instrument.js"],b["modules/sonification/instrumentDefinitions.js"],b["modules/sonification/Earcon.js"],b["modules/sonification/pointSonify.js"],b["modules/sonification/chartSonify.js"],b["modules/sonification/utilities.js"],b["modules/sonification/Timeline.js"]],function(b,l,e,n,m,g,q,k,c,a){var d=e.addEvent;e=e.extend;b.sonification={fadeOutDuration:20,
utilities:c,Instrument:n,instruments:m,Earcon:g,TimelineEvent:a.TimelineEvent,TimelinePath:a.TimelinePath,Timeline:a.Timeline};l.prototype.sonify=q.pointSonify;l.prototype.cancelSonify=q.pointCancelSonify;b.Series.prototype.sonify=k.seriesSonify;e(b.Chart.prototype,{sonify:k.chartSonify,pauseSonify:k.pause,resumeSonify:k.resume,rewindSonify:k.rewind,cancelSonify:k.cancel,getCurrentSonifyPoints:k.getCurrentPoints,setSonifyCursor:k.setCursor,resetSonifyCursor:k.resetCursor,resetSonifyCursorEnd:k.resetCursorEnd});
d(b.Chart,"init",function(){this.sonification={}})});n(b,"masters/modules/sonification.src.js",[],function(){})});
//# sourceMappingURL=sonification.js.map